/**
 * What Just Hit Me — Hitbox Editor dev server (separate tool, not part of the game).
 *
 *   npm run editor      ->  http://localhost:5174
 *
 * Serves the editor UI (this folder) at /, the game (repo root) at /game/ so the
 * editor can load it in a hidden iframe and reuse the real sprite registry, and
 * writes the authored boxes/alignment straight into the game source at
 * characters/hitbox-data.js via POST /api/save. No external dependencies.
 */
import http from "node:http";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { exec } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EDITOR_DIR = __dirname;                       // tools/editor
const GAME_ROOT = path.resolve(__dirname, "..", ".."); // repo root
const DATA_FILE = path.join(GAME_ROOT, "characters", "hitbox-data.js");
const PORT = 5174;

const MIME = {
  ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8", ".png": "image/png", ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg", ".gif": "image/gif", ".svg": "image/svg+xml", ".webp": "image/webp",
  ".ico": "image/x-icon", ".wav": "audio/wav", ".mp3": "audio/mpeg", ".ogg": "audio/ogg",
  ".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf"
};

function safeJoin(root, urlPath) {
  const p = path.normalize(path.join(root, decodeURIComponent(urlPath)));
  if (!p.startsWith(root)) return null;   // block path traversal
  return p;
}

async function serveFile(res, filePath, fallbackIndex) {
  try {
    let stat = await fs.stat(filePath).catch(() => null);
    if (stat && stat.isDirectory() && fallbackIndex) { filePath = path.join(filePath, fallbackIndex); stat = await fs.stat(filePath).catch(() => null); }
    if (!stat || !stat.isFile()) { res.writeHead(404); res.end("Not found"); return; }
    const buf = await fs.readFile(filePath);
    res.writeHead(200, { "Content-Type": MIME[path.extname(filePath).toLowerCase()] || "application/octet-stream", "Cache-Control": "no-store" });
    res.end(buf);
  } catch (e) { res.writeHead(500); res.end("Server error: " + e.message); }
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = ""; req.on("data", c => { data += c; if (data.length > 8e6) req.destroy(); });
    req.on("end", () => resolve(data)); req.on("error", reject);
  });
}

/** Serialize the authored data into the game-loaded source file. */
function renderDataFile(payload) {
  const hb = JSON.stringify(payload.hitboxes || {}, null, 2);
  const al = JSON.stringify(payload.spriteAlign || {}, null, 2);
  const cs = JSON.stringify(payload.charScale || {}, null, 2);
  const as = JSON.stringify(payload.charAnimSpeed || {}, null, 2);
  const af = JSON.stringify(payload.animFps || {}, null, 2);
  const at = JSON.stringify(payload.animTScale || {}, null, 2);
  const st = JSON.stringify(payload.charStats || {}, null, 2);
  return `/* AUTO-GENERATED by tools/editor (the Hitbox Editor). Do not edit by hand.
   Loaded by the game after js/hitboxes.js + the character modules; applies authored hit/hurt/attack/
   collision boxes, per-sprite alignment, per-character size, per-animation speed, and stats onto the registry. */
"use strict";
if (typeof HITBOXES !== "undefined") Object.assign(HITBOXES, ${hb});
if (typeof SPRITE_ALIGN !== "undefined") Object.assign(SPRITE_ALIGN, ${al});
if (typeof CHAR_SCALE !== "undefined") Object.assign(CHAR_SCALE, ${cs});
if (typeof CHAR_ANIM_SPEED !== "undefined") Object.assign(CHAR_ANIM_SPEED, ${as});
if (typeof ANIM_FPS !== "undefined") Object.assign(ANIM_FPS, ${af});
if (typeof ANIM_TSCALE !== "undefined") Object.assign(ANIM_TSCALE, ${at});
if (typeof CHAR_STATS !== "undefined") Object.assign(CHAR_STATS, ${st});
if (typeof applySpriteAlign === "function") applySpriteAlign();
if (typeof applyCharStats === "function") applyCharStats();
`;
}

const MANIFEST_FILE = path.join(GAME_ROOT, "characters", "sprite-manifest.js");
/** Recover per-sprite metadata from the existing manifest (regex per line: IMG_SPRITES["c"] = {...};). */
async function manifestMeta() {
  const out = {};
  try {
    const txt = await fs.readFile(MANIFEST_FILE, "utf8");
    const re = /^\s*IMG_SPRITES\[\s*"([^"]+)"\s*\]\s*=\s*(\{.*\})\s*;\s*$/gm; let m;
    while ((m = re.exec(txt))) { try { out[m[1]] = JSON.parse(m[2]); } catch (e) {} }
  } catch (e) {}
  return out;
}
/** Scan assets/characters/<char>/<animation>/<key>.png -> { char: { key: relSrc } }. */
async function scanSprites() {
  const out = {}, base = path.join(GAME_ROOT, "assets", "characters");
  let chars = []; try { chars = await fs.readdir(base); } catch (e) { return out; }
  for (const char of chars) {
    const cd = path.join(base, char); let st; try { st = await fs.stat(cd); } catch (e) { continue; }
    if (!st.isDirectory()) continue;
    let folders = []; try { folders = await fs.readdir(cd); } catch (e) { continue; }
    for (const folder of folders) {
      const fd = path.join(cd, folder); let fst; try { fst = await fs.stat(fd); } catch (e) { continue; }
      if (!fst.isDirectory()) continue;
      let files = []; try { files = await fs.readdir(fd); } catch (e) { continue; }
      for (const file of files) {
        if (!/\.png$/i.test(file)) continue;
        const key = file.replace(/\.png$/i, "");
        (out[char] = out[char] || {})[key] = "assets/characters/" + char + "/" + folder + "/" + file;
      }
    }
  }
  return out;
}
const _prefixOf = k => { const m = k.match(/^(.*?)(\d+[a-z]?|)$/i); return (m && m[1]) || k; };
/** Regenerate the manifest from a fresh folder scan, keeping known metadata and inferring new frames. */
async function rescanAndWriteManifest() {
  const scan = await scanSprites(), meta = await manifestMeta();
  const manifest = {}; let total = 0, added = 0;
  for (const char of Object.keys(scan)) {
    manifest[char] = {};
    for (const key of Object.keys(scan[char])) {
      total++;
      let m = meta[char] && meta[char][key];
      if (!m) { // new file: inherit metadata from a sibling in the same animation, else default
        added++;
        const pre = _prefixOf(key), sib = meta[char] && Object.keys(meta[char]).find(k => _prefixOf(k) === pre);
        m = (sib && meta[char][sib]) || { w: 95, h: 95 };
      }
      const e = { w: m.w, h: m.h, src: scan[char][key] };
      if (m.dx) e.dx = m.dx; if (m.foot) e.foot = m.foot;
      manifest[char][key] = e;
    }
  }
  let js = `/* AUTO-GENERATED sprite manifest — sprites live in assets/characters/<char>/<animation>/<key>.png.
   Rebuilds IMG_SPRITES from those folders. Regenerated by the editor server on rescan (add/remove files). */
"use strict";
if (typeof IMG_SPRITES !== "undefined") {
`;
  for (const char of Object.keys(manifest)) js += "  IMG_SPRITES[" + JSON.stringify(char) + "] = " + JSON.stringify(manifest[char]) + ";\n";
  js += "}\n";
  await fs.writeFile(MANIFEST_FILE, js, "utf8");
  return { total, added };
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, "http://localhost");
  const pathname = url.pathname;

  if (req.method === "POST" && pathname === "/api/rescan") {
    try { const r = await rescanAndWriteManifest();
      res.writeHead(200, { "Content-Type": "application/json" }); res.end(JSON.stringify({ ok: true, ...r }));
    } catch (e) { res.writeHead(500, { "Content-Type": "application/json" }); res.end(JSON.stringify({ ok: false, error: e.message })); }
    return;
  }

  if (req.method === "POST" && pathname === "/api/save") {
    try {
      const body = await readBody(req);
      const payload = JSON.parse(body || "{}");
      await fs.mkdir(path.dirname(DATA_FILE), { recursive: true });
      await fs.writeFile(DATA_FILE, renderDataFile(payload), "utf8");
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: true, file: path.relative(GAME_ROOT, DATA_FILE) }));
    } catch (e) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: false, error: e.message }));
    }
    return;
  }

  if (pathname.startsWith("/game/")) {
    const fp = safeJoin(GAME_ROOT, pathname.slice("/game".length));
    if (!fp) { res.writeHead(403); res.end("Forbidden"); return; }
    return serveFile(res, fp, "RUN_GAME.html");
  }

  // editor static (default)
  const fp = safeJoin(EDITOR_DIR, pathname === "/" ? "/index.html" : pathname);
  if (!fp) { res.writeHead(403); res.end("Forbidden"); return; }
  return serveFile(res, fp, "index.html");
});

const link = `http://localhost:${PORT}`;
function openBrowser() {
  if (process.env.NO_OPEN) return;
  const open = process.platform === "win32" ? `start "" "${link}"` : process.platform === "darwin" ? `open "${link}"` : `xdg-open "${link}"`;
  exec(open, () => {});
}

// If the port is taken it's almost certainly an editor already running: just open it and exit
// cleanly instead of crashing with EADDRINUSE.
server.on("error", (err) => {
  if (err && err.code === "EADDRINUSE") {
    console.log(`\n  An editor is already running at  ${link}  — opening that.`);
    console.log(`  (To restart fresh, close the other one first, or run:  npx kill-port ${PORT})\n`);
    openBrowser();
    process.exit(0);
  }
  throw err;
});

server.listen(PORT, () => {
  console.log(`\n  Hitbox Editor running at  ${link}`);
  console.log(`  Game served from          ${GAME_ROOT}`);
  console.log(`  Saves write               ${path.relative(GAME_ROOT, DATA_FILE)}\n`);
  openBrowser();
});
