/**
 * What Just Hit Me — Hitbox Editor dev server (separate tool, not part of the game).
 *
 *   npm run editor      ->  http://localhost:5174
 *
 * Serves the editor UI (this folder) at /, the game (repo root) at /game/ so the
 * editor can load it in a hidden iframe and reuse the real sprite registry, and
 * writes the authored boxes/alignment straight into the game source at
 * characters/hitbox-data.js via POST /api/save. No external dependencies.
 */
import http from "node:http";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { exec } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EDITOR_DIR = __dirname;                       // tools/editor
const GAME_ROOT = path.resolve(__dirname, "..", ".."); // repo root
const DATA_FILE = path.join(GAME_ROOT, "characters", "hitbox-data.js");
const PORT = 5174;

const MIME = {
  ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8", ".png": "image/png", ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg", ".gif": "image/gif", ".svg": "image/svg+xml", ".webp": "image/webp",
  ".ico": "image/x-icon", ".wav": "audio/wav", ".mp3": "audio/mpeg", ".ogg": "audio/ogg",
  ".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf"
};

function safeJoin(root, urlPath) {
  const p = path.normalize(path.join(root, decodeURIComponent(urlPath)));
  if (!p.startsWith(root)) return null;   // block path traversal
  return p;
}

async function serveFile(res, filePath, fallbackIndex) {
  try {
    let stat = await fs.stat(filePath).catch(() => null);
    if (stat && stat.isDirectory() && fallbackIndex) { filePath = path.join(filePath, fallbackIndex); stat = await fs.stat(filePath).catch(() => null); }
    if (!stat || !stat.isFile()) { res.writeHead(404); res.end("Not found"); return; }
    const buf = await fs.readFile(filePath);
    res.writeHead(200, { "Content-Type": MIME[path.extname(filePath).toLowerCase()] || "application/octet-stream", "Cache-Control": "no-store" });
    res.end(buf);
  } catch (e) { res.writeHead(500); res.end("Server error: " + e.message); }
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = ""; req.on("data", c => { data += c; if (data.length > 8e6) req.destroy(); });
    req.on("end", () => resolve(data)); req.on("error", reject);
  });
}

/** Serialize the authored data into the game-loaded source file. */
function renderDataFile(payload) {
  const hb = JSON.stringify(payload.hitboxes || {}, null, 2);
  const al = JSON.stringify(payload.spriteAlign || {}, null, 2);
  const cs = JSON.stringify(payload.charScale || {}, null, 2);
  return `/* AUTO-GENERATED by tools/editor (the Hitbox Editor). Do not edit by hand.
   Loaded by the game after js/hitboxes.js + the character modules; applies authored
   hit/hurt/attack/collision boxes, per-sprite alignment, and per-character size onto the registry. */
"use strict";
if (typeof HITBOXES !== "undefined") Object.assign(HITBOXES, ${hb});
if (typeof SPRITE_ALIGN !== "undefined") Object.assign(SPRITE_ALIGN, ${al});
if (typeof CHAR_SCALE !== "undefined") Object.assign(CHAR_SCALE, ${cs});
if (typeof applySpriteAlign === "function") applySpriteAlign();
`;
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, "http://localhost");
  const pathname = url.pathname;

  if (req.method === "POST" && pathname === "/api/save") {
    try {
      const body = await readBody(req);
      const payload = JSON.parse(body || "{}");
      await fs.mkdir(path.dirname(DATA_FILE), { recursive: true });
      await fs.writeFile(DATA_FILE, renderDataFile(payload), "utf8");
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: true, file: path.relative(GAME_ROOT, DATA_FILE) }));
    } catch (e) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: false, error: e.message }));
    }
    return;
  }

  if (pathname.startsWith("/game/")) {
    const fp = safeJoin(GAME_ROOT, pathname.slice("/game".length));
    if (!fp) { res.writeHead(403); res.end("Forbidden"); return; }
    return serveFile(res, fp, "RUN_GAME.html");
  }

  // editor static (default)
  const fp = safeJoin(EDITOR_DIR, pathname === "/" ? "/index.html" : pathname);
  if (!fp) { res.writeHead(403); res.end("Forbidden"); return; }
  return serveFile(res, fp, "index.html");
});

const link = `http://localhost:${PORT}`;
function openBrowser() {
  if (process.env.NO_OPEN) return;
  const open = process.platform === "win32" ? `start "" "${link}"` : process.platform === "darwin" ? `open "${link}"` : `xdg-open "${link}"`;
  exec(open, () => {});
}

// If the port is taken it's almost certainly an editor already running: just open it and exit
// cleanly instead of crashing with EADDRINUSE.
server.on("error", (err) => {
  if (err && err.code === "EADDRINUSE") {
    console.log(`\n  An editor is already running at  ${link}  — opening that.`);
    console.log(`  (To restart fresh, close the other one first, or run:  npx kill-port ${PORT})\n`);
    openBrowser();
    process.exit(0);
  }
  throw err;
});

server.listen(PORT, () => {
  console.log(`\n  Hitbox Editor running at  ${link}`);
  console.log(`  Game served from          ${GAME_ROOT}`);
  console.log(`  Saves write               ${path.relative(GAME_ROOT, DATA_FILE)}\n`);
  openBrowser();
});
