/* AUTO-GENERATED by tools/editor (the Map Editor). Do not edit by hand.
   Per-object position/size overrides + world limits for the stage. Loaded after js/map-system.js
   and before js/engine.js so world-limit overrides reach CFG in time. */
"use strict";
if (typeof MAP_DATA !== "undefined") {
  Object.assign(MAP_DATA.limits, {});
  Object.assign(MAP_DATA.objects, {});
}
if (typeof mapApplyLimits === "function") mapApplyLimits();
